FROM python:3.7.12-slim-buster

ENV ARGUS_DIRECTORY=/usr/local/argus
ENV DATA_DIRECTORY=${ARGUS_DIRECTORY}/data
RUN mkdir -p ${DATA_DIRECTORY}

ENV LOG_LEVEL=INFO
ENV LOG_DIRECTORY=/var/log/argus
RUN mkdir -p ${LOG_DIRECTORY}

COPY . ${ARGUS_DIRECTORY}/

WORKDIR ${ARGUS_DIRECTORY}

RUN pip install --no-cache .
