services:
  argus:
    build: .
    command: ["python", "argus/app.py", "find-new-listings"]
    restart: unless-stopped
    volumes:
        - ./data/argus:/var/argus
    env_file:
      - .env
    environment:
      - DB_LOCATION=/var/argus/argus.db

  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/config.yaml
    restart: unless-stopped
    volumes:
      - ./config/loki:/etc/loki

  grafana:
    restart: unless-stopped
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
#    ports:
#      - "3000:3000"
