name: deploy

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  run-checks:
    uses: ./.github/workflows/run-checks.yaml
  deploy:
    runs-on: ubuntu-latest
    needs: [ run-checks ]
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd argus
            git pull
            make start-prod
