name: pull-request

on:
  pull_request:
      types: [ "opened", "reopened", "synchronize", "edited" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'poetry'
      - run: poetry install
      - run: poetry run black argus
      - run: poetry run ruff check argus
      - run: poetry run ruff format argus
      - run: poetry run pytest argus
